
public class WordList
{
	private String[] wordList = {"aardvark","abolish","above","abroad","abrupt","absence","abstract","abundant","accede","accident","accuse","achieve","acreage","across","acute","admonish","adobe","adore","adroit","advance","advice","affect","agent","agree","ailment","airborne","albacore","alfalfa","allow","almond","aloud","aluminum","amateur","amber","amnesia","amount","analyze","ancestor","ancient","angle","angry","answer","antelope","antenna","anthem","antique","antler","anvil","anxious","apathy","apex","aphid","apology","apostle","apparel","appeal","appetite","apple","apso","aptitude","archery","arctic","arduous","area","argue","argument","army","around","arrest",
			"arson","artist","asbestos","asleep","asphalt","assembly","assume","asylum","athletic","attend","attorney","attract","audience","aunt","author","autumn","avarice","avenge","avid","award","aware","baboon","bachelor","bacon","bacteria","badger","baffle","bagel","baggage","bailiff","bairn","bakery","balance","baleen","balloon","ballot","baloney","banana","banjo","banner","banquet","barbecue","barely","bargain","barracks","barrier","basket","battle","bauxite","beacon","beagle","beetle","behave","belief","believe","benefit","betrayal","between","biannual","bicuspid","bicycle","bigger","binary","birth","birthday","biscuit","bison","bitter","bivalve","blade",
			"blanch","bland","blarney","blatant","blaze","bleak","blend","blight","blizzard","blossom","board","boll","bolster","bonanza","both","bother","bottle","bottom","boundary","boutique","brabble","braid","bravery","bread","breathe","breeze","bridal","bridge","broccoli","broil","brother","brought","browse","bruise","bubble","buffet","bugle","bulletin","buoyancy","burglar","burros","butcher","butter","button","cabbage","cacao","cactus","calcium","calendar","calorie","camera","camp","canary","candor","canine","canister","canteen","caprice","capture","carcass","cardiac","career","carnival","carpet","cascade","cashew","casket","castle","category","cattle",
			"caught","cedar","celery","cello","cement","cemetery","censer","century","certain","chafe","chance","change","changing","charm","chateau","cheddar","cheek","chicken","children","choice","choose","choral","chorus","chose","chronic","cider","circuit","circular","cirrus","cistern","citizen","citrus","clamor","cleanse","cleaver","clench","client","climate","climb","climbed","clipper","close","closet","cloth","clothes","clothing","clout","clown","clumsy","cluster","clutch","coach","coarse","cobalt","cochlea","coconut","colander","college","combat","comet","comfort","coming","command","complain","congress","contain","control","cornea","corner","cotton",
			"council","course","cozy","crack","crate","crave","crawl","crazy","creak","crease","creation","credible","crouton","currant","cursor","custom","cyclone","debonair","decanter","deceive","deceived","decipher","defense","descend","describe","desert","despair","dessert","develop","dilemma","diorama","disease","disguise","domestic","doubt","dulcimer","easily","endeavor","enemy","enigma","ensign","equinox","exceed","exercise","existent","exterior","falsify","familiar","fantasia","fastuous","fiercest","filet","first","forecast","forester","formerly","forty","fourth","freesia","frittata","fumble","furlough","gargoyle","genesis","genius","geologic","geyser","gimmick","gloxinia","gnaw",
			"gracious","grammar","grateful","grievous","guidance","hacienda","handsome","happily","height","heliport","hermit","hexagon","highway","hoarse","hologram","hoping","horse","humorist","ideally","inferior","injured","inviable","island","isle","isthmus","jelly","jeopardy","jinx","jostle","jubilee","judicial","justice","kilowatt","kinetic","knead","knit","knotting","koala","kumquat","later","league","legume","leopard","limerick","linoleum","loose","lose","loyalist","luggage","luncheon","lymph","macaroon","magazine","magnolia","majority","marathon","maritime","martial","mascot","matador","mediator","mediocre","memento","meringue","mignon","mileage","minimum","minutes","moccasin","molecule",
			"monocot","moraine","mortgage","moss","musician","myogenic","nauseous","nebula","nephew","ninety","ninth","node","nominee","noun","novelty","nuclear","nutrient","oasis","obituary","obstacle","opaque","opossum","optimism","orbit","ordinary","orient","origin","ornament","ostrich","oxygen","paltry","pancreas","papaya","park","past","pastoral","patience","peculiar","pedigree","pennant","pharaoh","pheasant","piece","pilot","pioneer","placate","planning","plaque","pliable","poignant","policies","polygon","pommel","porpoise","possess","possible","prima","proclaim","pronoun","pueblo","pursue","python","quasar","quibbled","quiet","quite","quizzes","quotient","rabies","raffia",
			"reality","realize","really","receptor","recorder","redeem","reelect","refinish","region","reindeer","relevant","religion","removed","replied","rescind","residual","resonant","rigatoni","rival","robbery","robot","rodeos","ruffian","safety","sanitize","sarong","scenery","scheme","scrabble","sergeant","service","shepherd","shimmer","shoal","shriek","siege","sieve","sleigh","smudge","society","soldier","solitude","spacious","specific","spectrum","sphere","squid","stanza","statue","stingy","straight","strategy","strength","stretch","struggle","subpoena","succeed","suite","summery","superior","surpass","surprise","surveyor","suspense","sweet","swivel","syllabus","sympathy","synonym","tapestry",
			"tariff","tastier","teakwood","tenor","teriyaki","terrier","thievery","thistle","though","throttle","through","thwart","tiger","tirade","tobacco","tomatoes","topiary","tortilla","trachea","traipse","trough","tundra","typical","umbrella","unique","uranium","vacancy","vacuum","vagabond","valiant","vane","variety","vault","vein","veracity","vicinity","vigorous","volume","wampum","wasted","weevil","weird","wholly","wild","would","wrench","xylem","xiphoid","xanadu","xylyl","xenia","yodel","yolk","your","zephyr","zircon","zoology","zwieback"};
	public WordList(){}
	public String getWord()
	{
		int length = wordList.length;
		int rand = (int)(Math.random()*length);
		return wordList[rand];
		
	}
}
